services:
  apache-php:
    build: .
    container_name: laravel-osssd-${CLUSTER_NAME}
    ports:
      - "1304:80"
    volumes:
      - .:/var/www/html
      # - ./storage:/var/www/html/storage
    env_file:
      - .env
